<?php

namespace app\modules\admin\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $alias
 * @property int|null $parent_id
 * @property int|null $status
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parent_id', 'status'], 'integer'],
            [['name', 'alias'], 'string', 'max' => 255],
        ];
    }

    public function beforeSave($insert)
    {
        $this->alias = createAlias($this->name);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Alias',
            'parent_id' => 'Родитель',
            'parentName' => 'Родитель',
            'status' => 'Статус',
        ];
    }

    public function getParent()
    {
        return Category::findOne($this->parent_id);
    }

    public function getParentName()
    {
        return $this->parent->name ?? '';
    }
}
